set -e
true
true
/student/jkarravula/courses/bcb5250/bcb5250-env/bin/python3 /public/ahnt/software/SPAdes-3.15.4-Linux/share/spades/spades_pipeline/scripts/preprocess_interlaced_reads.py --args_filename /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/split_input/tmp/interlaced --dst /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/split_input
true
true
/public/ahnt/software/SPAdes-3.15.4-Linux/bin/spades-hammer /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/corrected/configs/config.info
/student/jkarravula/courses/bcb5250/bcb5250-env/bin/python3 /public/ahnt/software/SPAdes-3.15.4-Linux/share/spades/spades_pipeline/scripts/compress_all.py --input_file /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/corrected/corrected.yaml --ext_python_modules_home /public/ahnt/software/SPAdes-3.15.4-Linux/share/spades --max_threads 16 --output_dir /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/corrected --gzip_output
true
true
/public/ahnt/software/SPAdes-3.15.4-Linux/bin/spades-core /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K21/configs/config.info
/public/ahnt/software/SPAdes-3.15.4-Linux/bin/spades-core /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K33/configs/config.info
/public/ahnt/software/SPAdes-3.15.4-Linux/bin/spades-core /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K55/configs/config.info
/public/ahnt/software/SPAdes-3.15.4-Linux/bin/spades-core /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K77/configs/config.info
/student/jkarravula/courses/bcb5250/bcb5250-env/bin/python3 /public/ahnt/software/SPAdes-3.15.4-Linux/share/spades/spades_pipeline/scripts/copy_files.py /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K77/before_rr.fasta /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/before_rr.fasta /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K77/assembly_graph_after_simplification.gfa /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/assembly_graph_after_simplification.gfa /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K77/final_contigs.fasta /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/contigs.fasta /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K77/first_pe_contigs.fasta /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/first_pe_contigs.fasta /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K77/strain_graph.gfa /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/strain_graph.gfa /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K77/scaffolds.fasta /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/scaffolds.fasta /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K77/scaffolds.paths /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/scaffolds.paths /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K77/assembly_graph_with_scaffolds.gfa /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/assembly_graph_with_scaffolds.gfa /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K77/assembly_graph.fastg /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/assembly_graph.fastg /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/K77/final_contigs.paths /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/contigs.paths
true
/student/jkarravula/courses/bcb5250/bcb5250-env/bin/python3 /public/ahnt/software/SPAdes-3.15.4-Linux/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/scaffolds.fasta --misc_dir /student/jkarravula/courses/bcb5250/week2-6lab/assembly_shortreads/reads/assembly_spades/misc --threshold_for_breaking_scaffolds 3
true
